// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, builder
import lombok.*;

// Import Hibernate annotation for automatic timestamp
import org.hibernate.annotations.CreationTimestamp;

// Import Java class for date and time
import java.time.LocalDateTime;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "audit_logs"
@Table(name = "audit_logs")

// Lombok: automatically generate getters
@Getter

// Lombok: automatically generate setters
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the AuditLog class
public class AuditLog {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Email of the user who performed the action
    @Column(name = "user_email")
    private String userEmail;


    // Action performed (example: CREATE_PRODUCT, DELETE_USER)
    // Cannot be null
    @Column(nullable = false)
    private String action;


    // Type of entity affected (example: Product, User, Sale)
    @Column(name = "entity_type")
    private String entityType;


    // ID of the affected entity (stored as text)
    @Column(name = "entity_id")
    private String entityId;


    // Organization related to this action
    @Column(name = "organization_id")
    private Long organizationId;


    // Shop related to this action
    @Column(name = "shop_id")
    private Long shopId;


    // Extra details about the action
    // Stored as TEXT for longer descriptions
    @Column(columnDefinition = "TEXT")
    private String details;


    // Automatically stores the time when the log was created
    @CreationTimestamp

    // Column name "created_at", cannot be updated later
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

}