// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, and builder
import lombok.*;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "categories"
@Table(name = "categories")

// Lombok: generate getters and setters
@Getter
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern for creating objects
@Builder

// Define the Category class
public class Category {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Category name column
    // Cannot be null and must be unique
    @Column(nullable = false, unique = true)
    private String name;


    // Description column
    // Stored as TEXT type in the database (for longer text)
    @Column(columnDefinition = "TEXT")
    private String description;

}