
// Define the package for this class.
package com.inventory.model;

// This import provides JPA annotations like @Entity and @Table.
import jakarta.persistence.*;

// This import provides Lombok annotations like @Getter and @Builder.
import lombok.*;

// This import provides automatic creation timestamp support.
import org.hibernate.annotations.CreationTimestamp;


// This import adds the LocalDateTime type for date and time values.
import java.time.LocalDateTime;

// This import adds ArrayList, a dynamic list implementation.
import java.util.ArrayList;

// This import adds the List interface.
import java.util.List;

// This annotation marks the class as a database entity.
@Entity

// This annotation sets the database table name for this entity.
@Table(name = "organizations")

// This annotation generates getter methods automatically.
@Getter

// This annotation generates setter methods automatically.
@Setter

// This annotation generates a no-argument constructor.
@NoArgsConstructor

// This annotation generates a constructor with all fields.
@AllArgsConstructor

// This annotation enables the builder pattern for object creation.
@Builder

// This line starts the Organization class definition.
// Define a public class.
public class Organization {

    
    // This annotation marks the field as the primary key.
    @Id
    
    // This annotation makes the ID auto-generated by the database.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    // This field stores the unique ID of the organization.
    private Long id;

    
    // This annotation makes sure the name column cannot be null.
    @Column(nullable = false)
    
    // This field stores the organization name.
    private String name;

    
    // This annotation auto-fills the field with creation time.
    @CreationTimestamp
    
    // This annotation sets the DB column name and makes it non-updatable.
    @Column(name = "created_at", updatable = false)
    
    // This field stores when the organization was created.
    private LocalDateTime createdAt;

    
    // This annotation defines one-to-many relation with shops.
    @OneToMany(mappedBy = "organization", cascade = CascadeType.ALL, orphanRemoval = false)
    
    // This keeps the default value when using Lombok builder.
    // cascade = CascadeType.ALL
    // Any operation done on Organization will also apply to its Shops
    // Example: save organization Ã¢â€ â€™ shops also saved
    //          delete organization Ã¢â€ â€™ shops also deleted

    // orphanRemoval = false
    // If a shop is removed from the organization's shop list,
    // it will NOT be deleted from the database automatically
    // It will just lose the relationship
    @Builder.Default
    
    // This list stores all shops that belong to this organization.
    private List<Shop> shops = new ArrayList<>();

    
    // This annotation defines one-to-many relation with users.
    @OneToMany(mappedBy = "organization", cascade = CascadeType.ALL, orphanRemoval = false)
    
    // This keeps the default value when using Lombok builder.
    @Builder.Default
    
    // This list stores all users that belong to this organization.
    private List<User> users = new ArrayList<>();

    
    // This brace ends the Organization class.
// Close the current code block.
}
