// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import validation annotations for checking input data
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

// Import Lombok to generate boilerplate code
import lombok.*;

// Import Hibernate annotation for automatic timestamp
import org.hibernate.annotations.CreationTimestamp;

// Import Java classes
import java.math.BigDecimal;
import java.time.LocalDateTime;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "products"
@Table(name = "products")

// Lombok: automatically generate getters
@Getter

// Lombok: automatically generate setters
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the Product class
public class Product {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Product name column
    // Cannot be null
    @Column(nullable = false)

    // Validation: name must not be blank
    @NotBlank(message = "Product name is required")
    private String name;


    // Product description column
    // Stored as TEXT for longer descriptions
    @Column(columnDefinition = "TEXT")
    private String description;


    // Product price column
    // precision=10 → total digits
    // scale=2 → digits after decimal
    @Column(nullable = false, precision = 10, scale = 2)

    // Validation: price cannot be null
    @NotNull(message = "Price is required")

    // Validation: price must be >= 0
    @DecimalMin(value = "0.00", inclusive = true, message = "Price cannot be negative")
    private BigDecimal price;


    // Product stock quantity
    @Column(name = "stock_quantity", nullable = false)

    // Validation: stock cannot be negative
    @Min(value = 0, message = "Stock quantity cannot be negative")
    private int stockQuantity;


    // Minimum stock level before warning
    @Column(name = "low_stock_threshold", nullable = false)

    // Validation: threshold must be at least 1
    @Min(value = 1, message = "Low stock threshold must be at least 1")
    private int lowStockThreshold;


    // Many products can belong to one category
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column in products table
    @JoinColumn(name = "category_id")
    private Category category;


    // Many products can be added by one seller (user)
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column linking to the seller
    @JoinColumn(name = "seller_id")
    private User seller;


    // Many products can belong to one shop
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column linking to the shop
    @JoinColumn(name = "shop_id")
    private Shop shop;


    // Indicates if the product is active or disabled
    @Column(nullable = false)

    // Keeps default value when using Lombok builder
    @Builder.Default
    private boolean active = true;


    // Automatically stores the time when the product is created
    @CreationTimestamp

    // Column name "created_at", cannot be updated later
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    // Helper method to check if product stock is low
    public boolean isLowStock() {

        // Returns true if current stock is less than threshold
        return this.stockQuantity < this.lowStockThreshold;
    }

}