// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to automatically generate common code
import lombok.*;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "roles"
@Table(name = "roles")

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create a constructor with no parameters
@NoArgsConstructor

// Lombok: create a constructor with all fields
@AllArgsConstructor

// Lombok: enables builder pattern for creating objects
@Builder

// Define the Role class
public class Role {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Role name column
    // Cannot be null and must be unique
    @Column(nullable = false, unique = true)
    private String name;

}