// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, builder
import lombok.*;

// Import Hibernate annotation for automatic timestamp
import org.hibernate.annotations.CreationTimestamp;

// Import Java classes
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "sales"
@Table(name = "sales")

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the Sale class
public class Sale {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Many sales can be made by one seller (user)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    // fetch = FetchType.LAZY means:
    // The related object will NOT be loaded from the database immediately
    // It will only be loaded when we actually access it
    // Example:
    // Sale sale = saleRepository.findById(1);
    // seller is NOT loaded yet
    // When we call:
    // sale.getSeller(); 
    // Now Hibernate loads the seller from the database

    // Foreign key column "seller_id" in sales table
    @JoinColumn(name = "seller_id", nullable = false)
    private User seller;


    // Plain buyer name stored directly in the sale
    @Column(name = "buyer_name")
    private String buyerName;


    // Many sales can happen in one shop
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column "shop_id"
    @JoinColumn(name = "shop_id")
    private Shop shop;


    // Total price of the sale
    // precision=12 → total digits
    // scale=2 → digits after decimal
    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount;


    // Automatically stores the time when the sale is created
    @CreationTimestamp

    // Column name "created_at", cannot be updated later
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    // One sale can contain many sale items (products in the sale)
    @OneToMany(mappedBy = "sale", cascade = CascadeType.ALL, orphanRemoval = true)

    // Keeps default value when using Lombok builder
    @Builder.Default

    // List storing all items included in this sale
    private List<SaleItem> saleItems = new ArrayList<>();

}