// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, builder
import lombok.*;

// Import Java class for precise decimal numbers (money values)
import java.math.BigDecimal;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "sale_items"
@Table(name = "sale_items")

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the SaleItem class
public class SaleItem {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Many sale items belong to one sale
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column "sale_id"
    @JoinColumn(name = "sale_id", nullable = false)
    private Sale sale;


    // Many sale items can refer to one product
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column "product_id"
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;


    // Quantity of this product in the sale
    @Column(nullable = false)
    private int quantity;


    // Price of one unit of the product at the time of sale
    // precision=10 → total digits
    // scale=2 → digits after decimal
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;


    // Total price for this item (price × quantity)
    // precision=12 → total digits
    // scale=2 → digits after decimal
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal subtotal;

}