// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, builder
import lombok.*;

// Import Hibernate annotation for automatic timestamp
import org.hibernate.annotations.CreationTimestamp;

// Import Java class for date and time
import java.time.LocalDateTime;


// Marks this class as a database entity (table)
@Entity

// Set the table name as "shop_managers"
// Unique constraint ensures a user cannot be manager of the same shop twice
@Table(
    name = "shop_managers",
    uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "shop_id"})
)

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the ShopManager class
public class ShopManager {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Many manager records can refer to one user
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column "user_id"
    @JoinColumn(name = "user_id", nullable = false)
    private User user;


    // Many manager records can refer to one shop
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column "shop_id"
    @JoinColumn(name = "shop_id", nullable = false)
    private Shop shop;


    // Automatically stores the time when the manager was assigned
    @CreationTimestamp

    // Column name "assigned_at", cannot be updated later
    @Column(name = "assigned_at", updatable = false)
    private LocalDateTime assignedAt;

}