// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to generate getters, setters, constructors, builder
import lombok.*;

// Import Hibernate annotation for automatic timestamp
import org.hibernate.annotations.CreationTimestamp;

// Import Java class for date and time
import java.time.LocalDateTime;


// Marks this class as a database entity (table)
@Entity

// Set the table name in the database as "stock_transactions"
@Table(name = "stock_transactions")

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create constructor with no parameters
@NoArgsConstructor

// Lombok: create constructor with all fields
@AllArgsConstructor

// Lombok: enable builder pattern
@Builder

// Define the StockTransaction class
public class StockTransaction {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Many stock transactions can belong to one product
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column "product_id"
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;


    // Quantity of stock involved in the transaction
    @Column(nullable = false)
    private int quantity;


    // Type of stock change
    // Example values: SALE, RESTOCK, INCREASE, DECREASE
    @Column(nullable = false)
    private String type;


    // Optional reason for the stock change
    // Example: damaged product, manual correction, etc.
    @Column
    private String reason;


    // Many transactions can happen in one shop
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column "shop_id"
    @JoinColumn(name = "shop_id")
    private Shop shop;


    // Automatically stores the time when the transaction is created
    @CreationTimestamp

    // Column name "created_at", cannot be updated later
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

}