// Define the package where this class belongs
package com.inventory.model;

// Import JPA annotations for database mapping
import jakarta.persistence.*;

// Import Lombok to reduce boilerplate code (getters, setters, constructors)
import lombok.*;

// Import Hibernate annotation to automatically store creation time
import org.hibernate.annotations.CreationTimestamp;

// Import Java classes
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;


// Marks this class as a database entity (a table)
@Entity

// Set the table name in the database as "users"
@Table(name = "users")

// Lombok: automatically generate getter methods
@Getter

// Lombok: automatically generate setter methods
@Setter

// Lombok: create a constructor with no arguments
@NoArgsConstructor

// Lombok: create a constructor with all fields
@AllArgsConstructor

// Lombok: enables builder pattern to create objects easily
@Builder
public class User {

    // Primary key of the table
    @Id

    // Auto-increment ID generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Username column, cannot be null
    @Column(nullable = false)
    private String username;


    // Email column, cannot be null and must be unique
    @Column(nullable = false, unique = true)
    private String email;


    // Password column, cannot be null
    @Column(nullable = false)
    private String password;


    // Keeps default value when using Lombok builder
    @Builder.Default

    // Column name in database is "is_manager"
    @Column(name = "is_manager")

    // Indicates whether the user is a manager or not
    private boolean manager = false;


    // Automatically stores the time when the user is created
    @CreationTimestamp

    // Column name "created_at", cannot be updated later
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    // User account must have an active status
    @Column(nullable = false)

    // Keeps default value when using Lombok builder
    @Builder.Default

    // Indicates whether the user account is active
    private boolean active = true;


    // Many users can belong to one organization
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column in users table
    @JoinColumn(name = "organization_id")
    private Organization organization;


    // Many users can belong to one shop
    @ManyToOne(fetch = FetchType.LAZY)

    // Foreign key column in users table
    @JoinColumn(name = "shop_id")
    private Shop shop;


    // A user can have many roles and a role can belong to many users
    @ManyToMany(fetch = FetchType.EAGER)

    // Creates a join table to connect users and roles
    @JoinTable(
        name = "user_roles",

        // Column that stores user id in the join table
        joinColumns = @JoinColumn(name = "user_id"),

        // Column that stores role id in the join table
        inverseJoinColumns = @JoinColumn(name = "role_id")
    )

    // Keeps default value when using Lombok builder
    @Builder.Default

    // Stores all roles assigned to this user
    // HashSet prevents duplicate roles
    private Set<Role> roles = new HashSet<>();
}